---
- name: Configure Apache httpd.conf
  template:
    src: "{{ apache_conf_file_template }}"
    dest: "{{ apache_conf_dir }}/{{ apache_conf_file }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0644'
  notify: restart apache
  become: true

- name: Get list of files in apache conf.d directory
  shell: ls -d -1 "{{ apache_confd_dir }}"/*
  changed_when: false
  check_mode: no
  register: apache_confd_dir_contents
  become: true

- name: Get list of managed file in apache conf.d directory
  shell: grep -l '^# Ansible managed:' "{{ apache_confd_dir }}"/*
  changed_when: false
  check_mode: no
  register: apache_confd_managed_files
  become: true

- name: Remove unmanged apache conf.d files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ apache_confd_dir_contents.stdout_lines }}"
  when: >
    item not in apache_confd_managed_files.stdout_lines
  become: true



