---
- name: Configure Apache httpd.conf
  template:
    src: "{{ apache_conf_file_template }}"
    dest: "{{ apache_conf_dir }}/{{ apache_conf_file }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    setype: httpd_config_t
    mode: '0644'
  notify: Test and Restart Apache
  become: true
