---
- name: Set fact apache_packages
  set_fact:
    apache_packages: "{{ _apache_packages }}"
  when: apache_packages is none

- name: Set fact apache_group
  set_fact:
    apache_group: "{{ _apache_group }}"
  when: apache_group is none

- name: Set fact apache_user
  set_fact:
    apache_user: "{{ _apache_user }}"
  when: apache_user is none

- name: Set fact apache_service
  set_fact:
    apache_service: "{{ _apache_service }}"
  when: apache_service is none

- name: Set fact apache_state
  set_fact:
    apache_state: "{{ _apache_state }}"
  when: apache_state is none

- name: Set fact apache_enabled
  set_fact:
    apache_enabled: "{{ _apache_enabled }}"
  when: apache_enabled is none

- name: Set fact apache_httpd_dir
  set_fact:
    apache_httpd_dir: "{{ _apache_httpd_dir }}"
  when: apache_httpd_dir is none

- name: Set fact apache_conf_file
  set_fact:
    apache_conf_file: "{{ _apache_conf_file }}"
  when: apache_conf_file is none

- name: Set fact apache_conf_dir
  set_fact:
    apache_conf_dir: "{{ _apache_conf_dir }}"
  when: apache_conf_dir is none

- name: Set fact apache_vhost_dir
  set_fact:
    apache_vhost_dir: "{{ _apache_vhost_dir }}"
  when: apache_vhost_dir is none

- name: Set fact apache_confd_dir
  set_fact:
    apache_confd_dir: "{{ _apache_confd_dir }}"
  when: apache_confd_dir is none

- name: Set fact apache_log_dir
  set_fact:
    apache_log_dir: "{{ _apache_log_dir }}"
  when: apache_log_dir is none

- name: Set fact apache_ssl_certs_dir
  set_fact:
    apache_ssl_certs_dir: "{{ _apache_ssl_certs_dir }}"
  when: apache_ssl_certs_dir is none

- name: Set fact apache_ssl_default_cert
  set_fact:
    apache_ssl_default_cert: "{{ _apache_ssl_default_cert }}"
  when: apache_ssl_default_cert is none

- name: Set fact apache_ssl_default_key
  set_fact:
    apache_ssl_default_key: "{{ _apache_ssl_default_key }}"
  when: apache_ssl_default_key is none

- name: Set fact apache_apachectl
  set_fact:
    apache_apachectl: "{{ _apache_apachectl }}"
  when: apache_apachectl is none
