---
- name: "Set VirtualHost filename for {{ item['server_name'] }}"
  set_fact:
    apache_vhost_filename: "{{ item['server_name'] }}_ssl"
  when: item['ssl'] | default(apache_vhost_ssl)

- name: "Set VirtualHost filename for {{ item['server_name'] }}"
  set_fact:
    apache_vhost_filename: "{{ item['server_name'] }}_non_ssl"
  when: not item['ssl'] | default(apache_vhost_ssl)

- name: Include listen.yml task list
  include: listen.yml

- name: "Manage VirtualHost {{ item['server_name'] }}"
  template:
    #    src: "{{ apache_vhosts_template }}"
    src: "{{ item['template'] | default(apache_vhosts_template) }}"
    dest: "{{ apache_vhost_dir }}/{{ apache_vhost_filename }}.conf"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
  notify: Test and Reload Apache
