---
- name: Test and Reload Apache
  command: "{{ _apachectl }} configtest"
  notify: Reload Apache

- name: Test and Restart Apache
  command: "{{ _apachectl }} configtest"
  notify: Restart Apache

- name: Reload Apache
  service:
    name: "{{ apache_service }}"
    state: 'reloaded'

- name: Restart Apache
  service:
    name: "{{ apache_service }}"
    state: 'restarted'
